review-service:
  url: http://review-service:8083
job-service:
  url: http://job-service:8082
company-service:
  url: http://company-service:8081

spring:
  application:
    name: company-service

  datasource:
    url: jdbc:postgresql://postgres:5432/companydb
    username: postgres
    password: lenin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: Asia/Kolkata

  rabbitmq:
    host: rabbitmq_jobboard
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka/